// Generated by esp32/tools/gen_layout.js — do not edit.
// Source: CodeCore/Sources/CodeCore/UI/{WatchLayout,FanLayout,RadialLayout}.swift
// Sebastian's hand-placed geometry, scaled by 2.071 into panel pixels
// and collapsed from the watch's two coordinate spaces into one.

#include "cr_layout.h"

static const cr_slot_t slots_code[] = {
    { { 70.414f, 169.822f }, 91.124f, 51.775f, { 70.414f, 235.431f }, 17.604f, 153.254f, 0 },
    { { 205.029f, 155.325f }, 91.124f, 51.775f, { 205.029f, 223.150f }, 17.604f, 153.254f, 1 },
    { { 339.644f, 169.822f }, 91.124f, 51.775f, { 339.644f, 235.431f }, 17.604f, 153.254f, 2 },
    { { 147.041f, 294.082f }, 91.124f, 51.775f, { 147.041f, 359.691f }, 17.604f, 153.254f, 3 },
    { { 263.017f, 294.082f }, 91.124f, 51.775f, { 263.017f, 359.691f }, 17.604f, 153.254f, 4 },
};
static const cr_slot_t slots_shock[] = {
    { { 147.041f, 157.147f }, 91.124f, 51.775f, { 147.041f, 224.973f }, 17.604f, 153.254f, 0 },
    { { 263.017f, 157.147f }, 91.124f, 51.775f, { 263.017f, 224.973f }, 17.604f, 153.254f, 1 },
};
static const cr_slot_t slots_grp_defib[] = {
    { { 76.627f, 244.378f }, 91.124f, 51.775f, { 76.627f, 309.987f }, 17.604f, 153.254f, 0 },
    { { 205.029f, 178.106f }, 91.124f, 51.775f, { 205.029f, 253.594f }, 17.604f, 153.254f, 1 },
    { { 337.573f, 244.378f }, 91.124f, 51.775f, { 337.573f, 319.866f }, 17.604f, 153.254f, 2 },
};
static const cr_slot_t slots_support[] = {
    { { 263.017f, 294.082f }, 91.124f, 51.775f, { 263.017f, 359.691f }, 17.604f, 153.254f, 0 },
    { { 205.029f, 155.325f }, 91.124f, 51.775f, { 205.029f, 223.150f }, 17.604f, 153.254f, 1 },
    { { 339.644f, 169.822f }, 91.124f, 51.775f, { 339.644f, 235.431f }, 17.604f, 153.254f, 2 },
    { { 147.041f, 294.082f }, 91.124f, 51.775f, { 147.041f, 359.691f }, 17.604f, 153.254f, 3 },
    { { 70.414f, 169.822f }, 91.124f, 51.775f, { 70.414f, 235.431f }, 17.604f, 153.254f, 4 },
};
static const cr_slot_t slots_grp_fluids[] = {
    { { 76.627f, 244.378f }, 91.124f, 51.775f, { 76.627f, 309.987f }, 17.604f, 153.254f, 0 },
    { { 205.029f, 178.106f }, 91.124f, 51.775f, { 205.029f, 243.715f }, 17.604f, 153.254f, 1 },
    { { 337.573f, 244.378f }, 91.124f, 51.775f, { 337.573f, 319.866f }, 17.604f, 153.254f, 2 },
};
static const cr_slot_t slots_grp_more[] = {
    { { 76.627f, 244.378f }, 91.124f, 51.775f, { 76.627f, 309.987f }, 17.604f, 153.254f, 0 },
    { { 205.029f, 155.325f }, 91.124f, 51.775f, { 205.029f, 223.150f }, 17.604f, 153.254f, 1 },
    { { 337.573f, 244.378f }, 91.124f, 51.775f, { 337.573f, 309.987f }, 17.604f, 153.254f, 2 },
};
static const cr_slot_t slots_events[] = {
    { { 89.053f, 162.636f }, 91.124f, 51.775f, { 89.053f, 230.461f }, 17.604f, 153.254f, 0 },
    { { 205.029f, 155.325f }, 91.124f, 51.775f, { 205.029f, 223.150f }, 17.604f, 153.254f, 1 },
    { { 321.005f, 162.636f }, 91.124f, 51.775f, { 321.005f, 230.461f }, 17.604f, 153.254f, 2 },
    { { 89.053f, 299.322f }, 91.124f, 51.775f, { 89.053f, 367.147f }, 17.604f, 153.254f, 3 },
    { { 205.029f, 292.011f }, 91.124f, 51.775f, { 205.029f, 359.836f }, 17.604f, 153.254f, 4 },
    { { 321.005f, 299.322f }, 91.124f, 51.775f, { 321.005f, 367.147f }, 17.604f, 153.254f, 5 },
};
static const cr_slot_t slots_grp_access[] = {
    { { 76.627f, 244.378f }, 91.124f, 51.775f, { 76.627f, 309.987f }, 17.604f, 153.254f, 0 },
    { { 205.029f, 178.106f }, 91.124f, 51.775f, { 205.029f, 243.715f }, 17.604f, 153.254f, 1 },
    { { 337.573f, 244.378f }, 91.124f, 51.775f, { 337.573f, 319.866f }, 17.604f, 153.254f, 2 },
};
static const cr_slot_t slots_grp_airway[] = {
    { { 147.041f, 178.106f }, 91.124f, 51.775f, { 147.041f, 243.715f }, 17.604f, 153.254f, 0 },
    { { 263.017f, 178.106f }, 91.124f, 51.775f, { 263.017f, 243.715f }, 17.604f, 153.254f, 1 },
    { { 76.627f, 306.508f }, 91.124f, 51.775f, { 76.627f, 372.117f }, 17.604f, 153.254f, 2 },
    { { 333.431f, 306.508f }, 91.124f, 51.775f, { 333.431f, 372.117f }, 17.604f, 153.254f, 3 },
};
static const cr_slot_t slots_grp_comms[] = {
    { { 107.692f, 198.816f }, 91.124f, 51.775f, { 107.692f, 264.425f }, 17.604f, 153.254f, 0 },
    { { 302.366f, 198.816f }, 91.124f, 51.775f, { 302.366f, 264.425f }, 17.604f, 153.254f, 1 },
};
static const cr_slot_t slots_grp_call[] = {
    { { 140.828f, 178.106f }, 91.124f, 51.775f, { 140.828f, 243.715f }, 17.604f, 153.254f, 0 },
    { { 269.230f, 178.106f }, 91.124f, 51.775f, { 269.230f, 243.715f }, 17.604f, 153.254f, 1 },
    { { 70.414f, 306.508f }, 91.124f, 51.775f, { 70.414f, 372.117f }, 17.604f, 153.254f, 2 },
    { { 333.431f, 306.508f }, 91.124f, 51.775f, { 333.431f, 372.117f }, 17.604f, 153.254f, 3 },
};
static const cr_slot_t slots_grp_arrival[] = {
    { { 140.828f, 178.106f }, 91.124f, 51.775f, { 140.828f, 243.715f }, 17.604f, 153.254f, 0 },
    { { 263.017f, 178.106f }, 91.124f, 51.775f, { 263.017f, 243.715f }, 17.604f, 153.254f, 1 },
    { { 70.414f, 306.508f }, 91.124f, 51.775f, { 70.414f, 372.117f }, 17.604f, 153.254f, 2 },
    { { 333.431f, 306.508f }, 91.124f, 51.775f, { 333.431f, 372.117f }, 17.604f, 153.254f, 3 },
};
static const cr_slot_t slots_grp_temp[] = {
    { { 205.029f, 178.106f }, 91.124f, 51.775f, { 205.029f, 243.715f }, 17.604f, 153.254f, 0 },
    { { 76.627f, 244.378f }, 91.124f, 51.775f, { 76.627f, 309.987f }, 17.604f, 153.254f, 1 },
    { { 337.573f, 244.378f }, 91.124f, 51.775f, { 337.573f, 319.866f }, 17.604f, 153.254f, 2 },
};
static const cr_slot_t slots_events_rosc[] = {
    { { 70.414f, 169.822f }, 91.124f, 51.775f, { 70.414f, 235.431f }, 17.604f, 153.254f, 0 },
    { { 205.029f, 155.325f }, 91.124f, 51.775f, { 205.029f, 223.150f }, 17.604f, 153.254f, 1 },
    { { 339.644f, 169.822f }, 91.124f, 51.775f, { 339.644f, 235.431f }, 17.604f, 153.254f, 2 },
    { { 147.041f, 294.082f }, 91.124f, 51.775f, { 147.041f, 359.691f }, 17.604f, 153.254f, 3 },
    { { 263.017f, 293.833f }, 91.124f, 51.775f, { 263.017f, 361.659f }, 17.604f, 153.254f, 4 },
};

static const char *const titles_code[] = { "Epinephrine", "Atropine", "Adenosine", "Amiodarone", "Lidocaine" };
static const char *const titles_shock[] = { "Defib", "Cardiovert" };
static const char *const titles_support[] = { "More", "Bicarb", "Calcium", "Dextrose", "Fluids" };
static const char *const titles_events[] = { "Rhythm", "Access", "Airway", "Comms", "Temp", "ROSC" };
static const char *const titles_events_rosc[] = { "Rhythm", "12-lead", "Drip", "Blood", "Temp" };
static const char *const titles_grp_defib[] = { "1st 20 J", "Next 40 J", "Max 100 J" };
static const char *const titles_grp_fluids[] = { "Blood", "10 mL/kg", "20 mL/kg" };
static const char *const titles_grp_more[] = { "Drip", "Magnesium", "Naloxone" };
static const char *const titles_grp_access[] = { "IV", "IO", "Art line" };
static const char *const titles_grp_airway[] = { "Intubation", "Bag", "Mask", "Trach" };
static const char *const titles_grp_comms[] = { "Call", "Arrival" };
static const char *const titles_grp_temp[] = { "Bair Hugger", "Arctic Sun", "Warm blankets" };
static const char *const titles_grp_call[] = { "Surgery", "Anesthesia", "ECMO", "Consult" };
static const char *const titles_grp_arrival[] = { "Surgery", "Anesthesia", "ECMO", "Consult" };

const cr_fan_t cr_fans[] = {
    { "code", "Meds", slots_code, 5, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 5, titles_code, 5 },
    { "shock", "Shock", slots_shock, 2, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 2, titles_shock, 2 },
    { "grp:defib", "Defib", slots_grp_defib, 3, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 3, titles_grp_defib, 3 },
    { "support", "Fluids", slots_support, 5, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 5, titles_support, 5 },
    { "grp:fluids", "Fluids", slots_grp_fluids, 3, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 3, titles_grp_fluids, 3 },
    { "grp:more", "More", slots_grp_more, 3, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 3, titles_grp_more, 3 },
    { "events", "Events", slots_events, 6, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 6, titles_events, 6 },
    { "grp:access", "Access", slots_grp_access, 3, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 3, titles_grp_access, 3 },
    { "grp:airway", "Airway", slots_grp_airway, 4, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 4, titles_grp_airway, 4 },
    { "grp:comms", "Comms", slots_grp_comms, 2, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 2, titles_grp_comms, 2 },
    { "grp:call", "Call", slots_grp_call, 4, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 4, titles_grp_call, 4 },
    { "grp:arrival", "Arrived", slots_grp_arrival, 4, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 4, titles_grp_arrival, 4 },
    { "grp:temp", "Temp", slots_grp_temp, 3, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 3, titles_grp_temp, 3 },
    { "events.rosc", "Events", slots_events_rosc, 5, { true, { 205.029f, 51.775f }, 33.136f, 18.639f, false }, true, 5, titles_events_rosc, 5 },
};
const size_t cr_fan_count = sizeof cr_fans / sizeof cr_fans[0];

const cr_arc_spec_t cr_arc = {
    .slot_pitch = 124.260f, .apex_y = 155.325f,
    .row_gap = 136.686f, .arc_drop = 12.426f,
    .side_inset = 49.704f, .label_gap = 8.284f,
    .label_box_height = 27.959f, .bubble_diameter = 91.124f,
    .glyph = 51.775f, .label_font = 17.604f, .label_width = 153.254f,
    .max_per_row = 3,
};

const cr_screen_t cr_screen = {
    .width = 410.058f, .height = 501.182f,
    .fan_origin = { 4.142f, 105.621f },
    .fan_width = 401.774f, .fan_height = 395.561f,
    .log_button = { { 60.059f, 49.704f }, 70.414f, 53.846f },
    .timers_button = { { 147.041f, 47.633f }, 70.414f, 53.846f },
    .pause_button = { { 205.029f, 337.573f }, 70.414f, 41.420f },
    .mute_button = { { 234.023f, 47.633f }, 70.414f, 53.846f },
    .flag_button = { { 360.354f, 113.905f }, 70.414f, 53.846f },
    .meds_puck = { { 62.130f, 434.910f }, 86.982f, 53.846f },
    .events_puck = { { 153.254f, 405.916f }, 86.982f, 53.846f },
    .fluids_puck = { { 352.070f, 434.910f }, 86.982f, 53.846f },
    .shock_puck = { { 256.804f, 405.916f }, 86.982f, 53.846f },
    .tap_glyph = { { 205.443f, 237.130f }, 27.959f, 27.959f },
    .rosc_heart = { { 205.029f, 250.591f }, 45.562f, 45.562f },
    .cpr_ring = { { 205.029f, 250.591f }, 194.674f, 16.568f },
    .drug_ring = { { 205.029f, 250.591f }, 165.680f, 10.355f },
    .vitals_ring = { { 205.029f, 250.591f }, 194.674f, 16.568f },
    .total_label = { { 160.503f, 474.259f }, 122.189f, 20.710f, 24.852f },
    .code_clock = { { 248.520f, 474.259f }, 115.976f, 27.959f, 33.136f },
    .cycle_chip = { { 205.029f, 202.958f }, 77.663f, 22.781f, 18.639f },
    .patient = { { 205.029f, 99.408f }, 227.810f, 28.994f, 18.639f },
    .start_text = { { 205.029f, 271.301f }, 186.390f, 20.710f, 24.852f },
    .pulse_label = { { 205.029f, 123.225f }, 285.798f, 22.781f, 20.710f },
    .countdown = { { 205.029f, 250.591f }, 110.799f, 62.130f, 51.775f },
    .drug_line = { { 205.029f, 287.869f }, 77.663f, 24.852f, 20.710f },
    .toast = { { 205.029f, 323.076f }, 310.650f, 33.136f, 22.781f },
    .paused_text = { { 205.029f, 250.591f }, 190.532f, 49.704f, 31.065f },
    .vitals_label = { { 205.029f, 123.225f }, 285.798f, 22.781f, 20.710f },
    .vitals_count = { { 205.029f, 250.591f }, 110.799f, 62.130f, 51.775f },
    .rosc_elapsed = { { 205.029f, 202.958f }, 157.396f, 22.781f, 20.710f },
    .vitals_prompt = { { 205.029f, 310.650f }, 157.396f, 28.994f, 16.568f },
    .re_arrest = { { 352.070f, 176.035f }, 107.692f, 45.562f, 18.639f },
    .handoff = { { 352.070f, 227.810f }, 107.692f, 45.562f, 18.639f },
    .chips = {
        { { 24.852f, 138.757f }, 107.692f, 55.917f, false, 16.568f },
        { { 12.426f, 194.674f }, 107.692f, 55.917f, false, 14.497f },
        { { 12.426f, 250.591f }, 107.692f, 55.917f, false, 14.497f },
        { { 24.852f, 306.508f }, 107.692f, 55.917f, false, 14.497f },
        { { 277.514f, 306.508f }, 107.692f, 55.917f, true, 16.568f },
        { { 298.224f, 250.591f }, 107.692f, 55.917f, true, 16.568f },
    },
    .chip_count = 6,
    .chip_count_font = 13.462f,
    .chip_timer_font = 19.675f,
    .pads = {
        .cancel = { { 205.029f, 414.200f }, 91.124f, 51.775f },
        .back   = { { 66.272f, 66.272f }, 91.124f, 51.775f },
        .hover_radius = 53.846f,
    },
};
