#!/bin/sh
# make_icons.sh — turn the Layout Bench's SVG icons into LVGL images.
#
# SF Symbols do not exist on this board, so the Bench's redraws are the icon
# set. Each one becomes an A8 (alpha-only) image: a MASK, not a picture, so
# LVGL tints it at runtime and one file serves every colour — red in the
# meds fan, blue in fluids, dark red on the exit pads.
#
#   cd esp32/firmware && sh tools/make_icons.sh
#
# Needs node, rsvg-convert (brew install librsvg), and a python with pypng +
# lz4 (esp32/build/toolvenv). Output is committed, so a normal build does
# not need any of them.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
firmware=$(dirname "$here")
repo=$(cd "$firmware/../.." && pwd)
bench="$repo/Tools/LayoutBench/index.html"
work="$firmware/../build/icons"
out="$firmware/main/icons"
python="$repo/esp32/build/toolvenv/bin/python"
converter="$firmware/managed_components/lvgl__lvgl/scripts/LVGLImage.py"

# Fan bubbles carry a 25 pt glyph on the watch; × 2.071 = 52 px here.
SIZE=${SIZE:-52}

command -v node >/dev/null || { echo "node not found"; exit 1; }
command -v rsvg-convert >/dev/null || { echo "rsvg-convert not found — brew install librsvg"; exit 1; }
[ -x "$python" ] || { echo "tool venv missing — python3 -m venv esp32/build/toolvenv && pip install pypng lz4"; exit 1; }
[ -f "$bench" ] || { echo "Layout Bench not found at $bench"; exit 1; }

rm -rf "$work"
mkdir -p "$work/svg" "$work/png" "$out"

echo "extracting SVGs from the Layout Bench…"
node "$here/extract_icons.js" "$bench" "$work/svg" > "$work/icons.tsv"

echo "rasterising at ${SIZE}px…"
while IFS="$(printf '\t')" read -r file symbol; do
    rsvg-convert -w "$SIZE" -h "$SIZE" -o "$work/png/$file.png" "$work/svg/$file.svg"
done < "$work/icons.tsv"

echo "converting to LVGL A8 images…"
rm -f "$out"/*.c
"$python" "$converter" --ofmt C --cf A8 --compress NONE -o "$out" "$work/png" > /dev/null

# The converter writes `#include "lvgl/lvgl.h"`, which is the path in LVGL's
# own tree. Inside an ESP-IDF component the header is plain "lvgl.h".
for file in "$out"/*.c; do
    sed 's|#include "lvgl/lvgl.h"|#include "lvgl.h"|' "$file" > "$file.tmp"
    mv "$file.tmp" "$file"
done

# Three event definitions carry SF Symbol names the Bench never redrew,
# because the watch never draws them: the menu tree supplies its own icon for
# each of those leaves (RadialMenu draws item.symbol, not definition.symbol).
# They are aliased to the nearest redrawn icon so a log row or a future
# screen can never come up blank.
cat >> "$work/icons.tsv" <<'ALIASES'
drop_fill	drop.circle.fill
thermometer_medium	thermometer.variable.and.figure
waveform_path_ecg	waveform.circle.fill
ALIASES

# A name → image lookup, so the UI asks for "syringe.fill" exactly as the
# watch app does and never hard-codes a C symbol.
{
    echo "// Generated by tools/make_icons.sh — do not edit."
    echo "// Source: Tools/LayoutBench/index.html (the icon set of record)."
    echo
    echo '#include "cr_icons.h"'
    echo
    echo "#include <string.h>"
    echo
    awk -F'\t' '{ print "LV_IMAGE_DECLARE(" $1 ");" }' "$work/icons.tsv"
    echo
    echo "static const struct { const char *symbol; const lv_image_dsc_t *dsc; } k_icons[] = {"
    awk -F'\t' '{ printf "    { \"%s\", &%s },\n", $2, $1 }' "$work/icons.tsv"
    echo "};"
    cat <<'C'

/// Resolves an SF Symbol name to its redrawn icon. Returns NULL when the
/// name is unknown — callers draw a fallback rather than crash, and the
/// build-time check below means that should never happen in practice.
const lv_image_dsc_t *cr_icon(const char *symbol)
{
    if (symbol == NULL) return NULL;
    for (size_t i = 0; i < sizeof k_icons / sizeof k_icons[0]; i++) {
        if (strcmp(k_icons[i].symbol, symbol) == 0) return k_icons[i].dsc;
    }
    return NULL;
}

size_t cr_icon_count(void)
{
    return sizeof k_icons / sizeof k_icons[0];
}
C
} > "$out/cr_icons.c"

# Every symbol the engine's data references must exist as an icon, or a
# button ships with a hole in it. Checked here, not discovered on the wrist.
missing=""
for symbol in $(grep -o '\.symbol = "[^"]*"' "$repo/esp32/core/src/cr_defaults.c" | sed 's/.*"\(.*\)"/\1/' | sort -u); do
    cut -f2 "$work/icons.tsv" | grep -qx "$symbol" || missing="$missing $symbol"
done
if [ -n "$missing" ]; then
    echo "FAILED — the Bench has no icon for:$missing"
    echo "  (add it to the ICONS table in Tools/LayoutBench/index.html, then re-run)"
    exit 1
fi

icons=$(wc -l < "$work/icons.tsv" | tr -d ' ')
bytes=$(cat "$out"/*.c | wc -c | tr -d ' ')
echo "done — $icons icons at ${SIZE}px, $((bytes / 1024)) kB of C, every drug/event symbol covered"
