// Generated by tools/make_icons.sh — do not edit.
// Source: Tools/LayoutBench/index.html (the icon set of record).

#include "cr_icons.h"

#include <string.h>

LV_IMAGE_DECLARE(syringe_fill);
LV_IMAGE_DECLARE(syringe);
LV_IMAGE_DECLARE(pills_fill);
LV_IMAGE_DECLARE(pill_fill);
LV_IMAGE_DECLARE(capsule_fill);
LV_IMAGE_DECLARE(ivfluid_bag_fill);
LV_IMAGE_DECLARE(cross_vial_fill);
LV_IMAGE_DECLARE(testtube_2);
LV_IMAGE_DECLARE(bandage_fill);
LV_IMAGE_DECLARE(cross_case_fill);
LV_IMAGE_DECLARE(cross_fill);
LV_IMAGE_DECLARE(cross_circle_fill);
LV_IMAGE_DECLARE(staroflife_fill);
LV_IMAGE_DECLARE(heart_fill);
LV_IMAGE_DECLARE(heart_slash_fill);
LV_IMAGE_DECLARE(bolt_heart_fill);
LV_IMAGE_DECLARE(arrow_down_heart_fill);
LV_IMAGE_DECLARE(arrow_up_heart_fill);
LV_IMAGE_DECLARE(heart_circle_fill);
LV_IMAGE_DECLARE(waveform_path_ecg);
LV_IMAGE_DECLARE(waveform);
LV_IMAGE_DECLARE(gauge_medium);
LV_IMAGE_DECLARE(stethoscope);
LV_IMAGE_DECLARE(drop_fill);
LV_IMAGE_DECLARE(drop_halffull);
LV_IMAGE_DECLARE(drop_triangle_fill);
LV_IMAGE_DECLARE(thermometer_medium);
LV_IMAGE_DECLARE(thermometer_high);
LV_IMAGE_DECLARE(thermometer_low);
LV_IMAGE_DECLARE(lungs_fill);
LV_IMAGE_DECLARE(facemask_fill);
LV_IMAGE_DECLARE(wind);
LV_IMAGE_DECLARE(humidity_fill);
LV_IMAGE_DECLARE(nose_fill);
LV_IMAGE_DECLARE(mouth_fill);
LV_IMAGE_DECLARE(brain_fill);
LV_IMAGE_DECLARE(brain_head_profile);
LV_IMAGE_DECLARE(eye_fill);
LV_IMAGE_DECLARE(ear_fill);
LV_IMAGE_DECLARE(figure_walk);
LV_IMAGE_DECLARE(figure_fall);
LV_IMAGE_DECLARE(bed_double_fill);
LV_IMAGE_DECLARE(allergens_fill);
LV_IMAGE_DECLARE(microbe_fill);
LV_IMAGE_DECLARE(phone_fill);
LV_IMAGE_DECLARE(person_2_fill);
LV_IMAGE_DECLARE(person_crop_circle_fill);
LV_IMAGE_DECLARE(bell_fill);
LV_IMAGE_DECLARE(list_bullet_clipboard_fill);
LV_IMAGE_DECLARE(doc_text_fill);
LV_IMAGE_DECLARE(chart_line_uptrend_xyaxis);
LV_IMAGE_DECLARE(bolt_fill);
LV_IMAGE_DECLARE(bolt_circle_fill);
LV_IMAGE_DECLARE(exclamationmark_triangle_fill);
LV_IMAGE_DECLARE(checkmark_circle_fill);
LV_IMAGE_DECLARE(xmark_circle_fill);
LV_IMAGE_DECLARE(minus_circle_fill);
LV_IMAGE_DECLARE(plus_circle_fill);
LV_IMAGE_DECLARE(flag_fill);
LV_IMAGE_DECLARE(snowflake);
LV_IMAGE_DECLARE(flame_fill);
LV_IMAGE_DECLARE(scissors);
LV_IMAGE_DECLARE(timer);
LV_IMAGE_DECLARE(stopwatch_fill);
LV_IMAGE_DECLARE(clock_fill);
LV_IMAGE_DECLARE(alarm_fill);
LV_IMAGE_DECLARE(arrow_counterclockwise);
LV_IMAGE_DECLARE(square_grid_2x2_fill);
LV_IMAGE_DECLARE(list_bullet);
LV_IMAGE_DECLARE(pause_fill);
LV_IMAGE_DECLARE(play_fill);
LV_IMAGE_DECLARE(speaker_wave_2_fill);
LV_IMAGE_DECLARE(speaker_slash_fill);
LV_IMAGE_DECLARE(hand_tap_fill);
LV_IMAGE_DECLARE(gearshape_fill);
LV_IMAGE_DECLARE(pencil_circle_fill);
LV_IMAGE_DECLARE(chevron_backward);
LV_IMAGE_DECLARE(xmark);
LV_IMAGE_DECLARE(hare_fill);
LV_IMAGE_DECLARE(pause_circle_fill);
LV_IMAGE_DECLARE(cube_fill);
LV_IMAGE_DECLARE(ellipsis);
LV_IMAGE_DECLARE(target);
LV_IMAGE_DECLARE(waveform_path);
LV_IMAGE_DECLARE(waveform_path_ecg_rectangle);
LV_IMAGE_DECLARE(person_2_wave_2_fill);
LV_IMAGE_DECLARE(figure_walk_arrival);
LV_IMAGE_DECLARE(ivfluid_bag);
LV_IMAGE_DECLARE(square_stack_3d_up_fill);
LV_IMAGE_DECLARE(tortoise_fill);
LV_IMAGE_DECLARE(waveform_slash);
LV_IMAGE_DECLARE(diamond_fill);
LV_IMAGE_DECLARE(hexagon_fill);
LV_IMAGE_DECLARE(bubbles_and_sparkles_fill);
LV_IMAGE_DECLARE(balloon_fill);
LV_IMAGE_DECLARE(cylinder_fill);
LV_IMAGE_DECLARE(arrow_down_to_line_compact);
LV_IMAGE_DECLARE(moon_zzz_fill);
LV_IMAGE_DECLARE(arrow_triangle_2_circlepath);
LV_IMAGE_DECLARE(drop_fill);
LV_IMAGE_DECLARE(thermometer_medium);
LV_IMAGE_DECLARE(waveform_path_ecg);

static const struct { const char *symbol; const lv_image_dsc_t *dsc; } k_icons[] = {
    { "syringe.fill", &syringe_fill },
    { "syringe", &syringe },
    { "pills.fill", &pills_fill },
    { "pill.fill", &pill_fill },
    { "capsule.fill", &capsule_fill },
    { "ivfluid.bag.fill", &ivfluid_bag_fill },
    { "cross.vial.fill", &cross_vial_fill },
    { "testtube.2", &testtube_2 },
    { "bandage.fill", &bandage_fill },
    { "cross.case.fill", &cross_case_fill },
    { "cross.fill", &cross_fill },
    { "cross.circle.fill", &cross_circle_fill },
    { "staroflife.fill", &staroflife_fill },
    { "heart.fill", &heart_fill },
    { "heart.slash.fill", &heart_slash_fill },
    { "bolt.heart.fill", &bolt_heart_fill },
    { "arrow.down.heart.fill", &arrow_down_heart_fill },
    { "arrow.up.heart.fill", &arrow_up_heart_fill },
    { "heart.circle.fill", &heart_circle_fill },
    { "waveform.path.ecg", &waveform_path_ecg },
    { "waveform", &waveform },
    { "gauge.medium", &gauge_medium },
    { "stethoscope", &stethoscope },
    { "drop.fill", &drop_fill },
    { "drop.halffull", &drop_halffull },
    { "drop.triangle.fill", &drop_triangle_fill },
    { "thermometer.medium", &thermometer_medium },
    { "thermometer.high", &thermometer_high },
    { "thermometer.low", &thermometer_low },
    { "lungs.fill", &lungs_fill },
    { "facemask.fill", &facemask_fill },
    { "wind", &wind },
    { "humidity.fill", &humidity_fill },
    { "nose.fill", &nose_fill },
    { "mouth.fill", &mouth_fill },
    { "brain.fill", &brain_fill },
    { "brain.head.profile", &brain_head_profile },
    { "eye.fill", &eye_fill },
    { "ear.fill", &ear_fill },
    { "figure.walk", &figure_walk },
    { "figure.fall", &figure_fall },
    { "bed.double.fill", &bed_double_fill },
    { "allergens.fill", &allergens_fill },
    { "microbe.fill", &microbe_fill },
    { "phone.fill", &phone_fill },
    { "person.2.fill", &person_2_fill },
    { "person.crop.circle.fill", &person_crop_circle_fill },
    { "bell.fill", &bell_fill },
    { "list.bullet.clipboard.fill", &list_bullet_clipboard_fill },
    { "doc.text.fill", &doc_text_fill },
    { "chart.line.uptrend.xyaxis", &chart_line_uptrend_xyaxis },
    { "bolt.fill", &bolt_fill },
    { "bolt.circle.fill", &bolt_circle_fill },
    { "exclamationmark.triangle.fill", &exclamationmark_triangle_fill },
    { "checkmark.circle.fill", &checkmark_circle_fill },
    { "xmark.circle.fill", &xmark_circle_fill },
    { "minus.circle.fill", &minus_circle_fill },
    { "plus.circle.fill", &plus_circle_fill },
    { "flag.fill", &flag_fill },
    { "snowflake", &snowflake },
    { "flame.fill", &flame_fill },
    { "scissors", &scissors },
    { "timer", &timer },
    { "stopwatch.fill", &stopwatch_fill },
    { "clock.fill", &clock_fill },
    { "alarm.fill", &alarm_fill },
    { "arrow.counterclockwise", &arrow_counterclockwise },
    { "square.grid.2x2.fill", &square_grid_2x2_fill },
    { "list.bullet", &list_bullet },
    { "pause.fill", &pause_fill },
    { "play.fill", &play_fill },
    { "speaker.wave.2.fill", &speaker_wave_2_fill },
    { "speaker.slash.fill", &speaker_slash_fill },
    { "hand.tap.fill", &hand_tap_fill },
    { "gearshape.fill", &gearshape_fill },
    { "pencil.circle.fill", &pencil_circle_fill },
    { "chevron.backward", &chevron_backward },
    { "xmark", &xmark },
    { "hare.fill", &hare_fill },
    { "pause.circle.fill", &pause_circle_fill },
    { "cube.fill", &cube_fill },
    { "ellipsis", &ellipsis },
    { "target", &target },
    { "waveform.path", &waveform_path },
    { "waveform.path.ecg.rectangle", &waveform_path_ecg_rectangle },
    { "person.2.wave.2.fill", &person_2_wave_2_fill },
    { "figure.walk.arrival", &figure_walk_arrival },
    { "ivfluid.bag", &ivfluid_bag },
    { "square.stack.3d.up.fill", &square_stack_3d_up_fill },
    { "tortoise.fill", &tortoise_fill },
    { "waveform.slash", &waveform_slash },
    { "diamond.fill", &diamond_fill },
    { "hexagon.fill", &hexagon_fill },
    { "bubbles.and.sparkles.fill", &bubbles_and_sparkles_fill },
    { "balloon.fill", &balloon_fill },
    { "cylinder.fill", &cylinder_fill },
    { "arrow.down.to.line.compact", &arrow_down_to_line_compact },
    { "moon.zzz.fill", &moon_zzz_fill },
    { "arrow.triangle.2.circlepath", &arrow_triangle_2_circlepath },
    { "drop.circle.fill", &drop_fill },
    { "thermometer.variable.and.figure", &thermometer_medium },
    { "waveform.circle.fill", &waveform_path_ecg },
};

/// Resolves an SF Symbol name to its redrawn icon. Returns NULL when the
/// name is unknown — callers draw a fallback rather than crash, and the
/// build-time check below means that should never happen in practice.
const lv_image_dsc_t *cr_icon(const char *symbol)
{
    if (symbol == NULL) return NULL;
    for (size_t i = 0; i < sizeof k_icons / sizeof k_icons[0]; i++) {
        if (strcmp(k_icons[i].symbol, symbol) == 0) return k_icons[i].dsc;
    }
    return NULL;
}

size_t cr_icon_count(void)
{
    return sizeof k_icons / sizeof k_icons[0];
}
